### ISSUE TITLE
Can't find CHINACACHE_CHANNEL_IDS

### ISSUE THREAD

**Issue by Myasnik2000** [trivago/exporter-chinacache#6]
Hi everyone ,  where  can I find CHINACACHE_CHANNEL_IDS ?

**Comment by mre** [comment]
I guess you can find that information in your account. There was also a document about the API where they described it I guess. Not sure if it was internal or not. Sorry, but I don't have any further information.

**Comment by iwilltry42** [comment]
Hi @Myasnik2000 I just found the API docs I used back then, but there's no info about how to retrieve the Channel IDs... they're just used as parameters for every query in there.
So I guess as  @mre said, it's probably a detail to be found in your account information.

**Comment by Myasnik2000** [comment]
Thanks guys for help , I'v found it
